// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBu5p2XAFCfdoKmrKwROG25KbiE0-HfZY',
    appId: '1:275372109714:web:3d4a0eea8521d618b8db4b',
    messagingSenderId: '275372109714',
    projectId: 'bizease-fe390',
    authDomain: 'bizease-fe390.firebaseapp.com',
    storageBucket: 'bizease-fe390.firebasestorage.app',
    measurementId: 'G-Q7WB55Z742',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0yTzcW_-BZxbYXnAwtVFlW28FLoyLqQ',
    appId: '1:275372109714:android:1ee2c63a0d69d9f3b8db4b',
    messagingSenderId: '275372109714',
    projectId: 'bizease-fe390',
    storageBucket: 'bizease-fe390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlHfIyx3R12ugUslrmJiYLFgByLBogEY',
    appId: '1:275372109714:ios:8d4ebcee8d7bb0c3b8db4b',
    messagingSenderId: '275372109714',
    projectId: 'bizease-fe390',
    storageBucket: 'bizease-fe390.firebasestorage.app',
    iosBundleId: 'com.example.bizEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlHfIyx3R12ugUslrmJiYLFgByLBogEY',
    appId: '1:275372109714:ios:8d4ebcee8d7bb0c3b8db4b',
    messagingSenderId: '275372109714',
    projectId: 'bizease-fe390',
    storageBucket: 'bizease-fe390.firebasestorage.app',
    iosBundleId: 'com.example.bizEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBu5p2XAFCfdoKmrKwROG25KbiE0-HfZY',
    appId: '1:275372109714:web:a2de4e6076e1c245b8db4b',
    messagingSenderId: '275372109714',
    projectId: 'bizease-fe390',
    authDomain: 'bizease-fe390.firebaseapp.com',
    storageBucket: 'bizease-fe390.firebasestorage.app',
    measurementId: 'G-ZQ1H58CDNL',
  );

}